version: '3.7'

services:
  consulting-website:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 3000:3000
    volumes:
      - "./:/usr/src/app/"
    env_file: 
      - .env